/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "blfpfzmcsblcdhitklja"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJsZnBmem1jc2JsY2RoaXRrbGphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzcwMTQxNTcsImV4cCI6MjA5MjU5MDE1N30.aDoaEaScUcoUYETv-HuFsXvK32mGY-DufMxW1r8U6us"